nameOverride: ""
fullnameOverride: ""

namespaceOverride: default

global:
  imageRegistry: docker.io
  imageOwner: buiducthien090605
  imagePullPolicy: Always

  serviceHost: api.ecom.local
  ingressClassName: nginx

  otel:
    exporterEndpoint: http://jaeger:4318/v1/traces

  rabbitmq:
    url: amqp://rabbitmq:5672

  storage:
    mode: local
    localClassName: hostpath
    distributedClassName: longhorn

  storageClass:
    name: hostpath
    create: false
    provisioner: rancher.io/local-path
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    annotations: {}
    parameters: {}

configmap:
  productService:
    port: "3001"
    otelServiceName: product-service
  orderService:
    port: "3002"
    otelServiceName: order-service
    productServiceUrl: http://product-service:3001
  inventoryService:
    port: "3003"
    otelServiceName: inventory-service

secrets:
  mongodb:
    productUri: mongodb://<username>:<password>@product-mongodb.example.local:27017/productdb?authSource=admin
    orderUri: mongodb://<username>:<password>@order-mongodb.example.local:27017/orderdb?authSource=admin
    inventoryUri: mongodb://<username>:<password>@inventory-mongodb.example.local:27017/inventorydb?authSource=admin

product-service:
  enabled: true
  replicaCount: 2
  containerPort: 3001
  image:
    repository: my-product-service
    tag: sha-0000000
  service:
    type: ClusterIP
    port: 3001
    canaryPort: 3001
  ingress:
    enabled: true
    path: /api/products
    pathType: Prefix
    annotations: {}
  rollout:
    enabled: true
    steps:
      - setWeight: 20
      - pause:
          duration: 60s
      - setWeight: 60
      - pause:
          duration: 60s
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilization: 60

order-service:
  enabled: true
  replicaCount: 2
  containerPort: 3002
  image:
    repository: my-order-service
    tag: sha-0000000
  service:
    type: ClusterIP
    port: 3002
    canaryPort: 3002
  ingress:
    enabled: true
    path: /api/orders
    pathType: Prefix
    annotations: {}
  rollout:
    enabled: true
    steps:
      - setWeight: 20
      - pause:
          duration: 60s
      - setWeight: 60
      - pause:
          duration: 60s
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilization: 60

inventory-service:
  enabled: true
  replicaCount: 2
  containerPort: 3003
  image:
    repository: my-inventory-service
    tag: sha-0000000
  service:
    type: ClusterIP
    port: 3003
    canaryPort: 3003
  rollout:
    enabled: true
    steps:
      - setWeight: 20
      - pause:
          duration: 60s
      - setWeight: 60
      - pause:
          duration: 60s
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilization: 60

rabbitmq:
  enabled: true
  replicaCount: 1
  image:
    repository: rabbitmq
    tag: 3.13-management-alpine
  service:
    type: ClusterIP
    amqpPort: 5672
    managementPort: 15672
  persistence:
    enabled: true
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi
