# events {}

# http {

#     upstream product_upstream {
#         ip_hash;  
# server product-service:3001 max_fails=3 fail_timeout=10s;
#     }

#     server {
#         listen 80;

#         location /api/products {
#             proxy_pass http://product_upstream;
#         }
#     }
# }


events {
    worker_connections 1024;
}

http {
    # 1. Upstream cho Product Service
    upstream product_cluster {
        server product-service:3001; 
    }

    # 2. Upstream cho Order Service
    upstream order_cluster {
        server order-service:3002;
    }

    # 3. Upstream cho Inventory Service
    upstream inventory_cluster {
        server inventory-service:3003;
    }

    server {
        listen 80;

        # Route cho API Sản phẩm
        location /api/products {
            proxy_pass http://product_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route cho API Đơn hàng
        location /api/orders {
            proxy_pass http://order_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route cho API Kho hàng
        location /api/inventory {
            proxy_pass http://inventory_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}