apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    {{- include "ecom-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: message-broker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        app.kubernetes.io/component: message-broker
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.amqpPort }}
              name: amqp
            - containerPort: {{ .Values.service.managementPort }}
              name: management
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.amqpPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.amqpPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: {{ default "rabbitmq-data-pvc" .Values.persistence.existingClaim }}
      {{- end }}
