apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  labels:
    {{- include "ecom-app.labels" . | nindent 4 }}
type: Opaque
data:
  PRODUCT_MONGO_URI: {{ .Values.secrets.mongodb.productUri | b64enc | quote }}
  ORDER_MONGO_URI: {{ .Values.secrets.mongodb.orderUri | b64enc | quote }}
  INVENTORY_MONGO_URI: {{ .Values.secrets.mongodb.inventoryUri | b64enc | quote }}
