apiVersion: v1
kind: Secret
metadata:
  name: git-creds-example
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd-image-updater
type: Opaque
stringData:
  username: "<github-username>"
  password: "<github-personal-access-token>"
