apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd-image-updater
type: Opaque
stringData:
  username: buiducthien090605
  password: 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
