apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    {{- include "ecom-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: inventory-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: inventory-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
