apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    {{- include "ecom-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-canary
  labels:
    {{- include "ecom-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
    rollouts.argoproj.io/service-role: canary
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.canaryPort }}
      targetPort: {{ .Values.containerPort }}
