apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: order-service
  labels:
    {{- include "ecom-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: order-service
  strategy:
    canary:
      stableService: order-service
      canaryService: order-service-canary
      trafficRouting:
        nginx:
          stableIngress: order-service-ingress
      steps:
        {{- toYaml .Values.rollout.steps | nindent 8 }}
  template:
    metadata:
      labels:
        app: order-service
        app.kubernetes.io/component: order-service
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.global.imageOwner }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: order-service-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: ORDER_MONGO_URI
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
